### ISSUE TITLE
zero-byte ClientId during CONNECT is not allowed

### ISSUE THREAD

**Issue by hirokiht** [ithinuel/mqttsn-packet#2]
The ClientId for MQTT-SN Connect is defined as the same in MQTT, therefore an anonymous client should be allowed if CleanSession is set to 1.

**Comment by ithinuel** [comment]
Hello,

Sorry for the delay.
I'm not sure about that.

[MQTT-SN v1.2](http://mqtt.org/new/wp-content/uploads/2009/06/MQTT-SN_spec_v1.2.pdf) was published on `14 November 2013` and so references [MQTT v3.1](http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/MQTT_V3.1_Protocol_Specific.pdf) not [MQTT v3.1.1](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf) whose publication date is on `29 October 2014`.
I could not find anything on MQTT v3.1 spec about CleanSession and zero-byte ClientId.
Also, the MQTT-SN v1.3 specification says :

> ClientId: same as with MQTT, contains the client id which is a **1-23** character long string which uniquely identifies the client to the server.
